### ISSUE TITLE
Ошибка при запуске cms/init

### ISSUE THREAD

**Issue by porcelanosa** [skeeks-cms/cms#77]
Ставим проект магазина
```
composer create-project --no-install --prefer-dist skeeks/app-shop skeeks-demo.dev
Installing skeeks/app-shop (1.1.1)
  - Installing skeeks/app-shop (1.1.1): Downloading (100%)
Created project in skeeks-demo.dev
```
все ОК - 
composer -install проходит без проблема 
В конце запускается postInstall
```
 skeeks\cms\console\Composer::postInstall
        postInstall
                tmp web config is generated
                tmp console config is generated
```
Дальше ошибка вот такая:
```
yii cms/init
Exception 'yii\base\InvalidConfigException' with message 'The configuration for the "cmsAgent" component must contain a "class" element.'

in E:\domains\skeeks-demo.dev\vendor\yiisoft\yii2\di\ServiceLocator.php:202

Stack trace:
#0 E:\domains\skeeks-demo.dev\vendor\yiisoft\yii2\di\ServiceLocator.php(258): yii\di\ServiceLocator->set('cmsAgent', Array)
#1 E:\domains\skeeks-demo.dev\vendor\yiisoft\yii2\base\Component.php(169): yii\di\ServiceLocator->setComponents(Array)
#2 E:\domains\skeeks-demo.dev\vendor\yiisoft\yii2\BaseYii.php(521): yii\base\Component->__set('components', Array)
#3 E:\domains\skeeks-demo.dev\vendor\yiisoft\yii2\base\Object.php(105): yii\BaseYii::configure(Object(yii\console\Application), Array)
#4 E:\domains\skeeks-demo.dev\vendor\yiisoft\yii2\base\Application.php(206): yii\base\Object->__construct(Array)
#5 E:\domains\skeeks-demo.dev\vendor\yiisoft\yii2\console\Application.php(89): yii\base\Application->__construct(Array)
#6 E:\domains\skeeks-demo.dev\vendor\skeeks\cms\app-console.php(25): yii\console\Application->__construct(Array)
#7 E:\domains\skeeks-demo.dev\yii(22): include('E:\\domains\\skee...')
#8 {main}
```

**Comment by skeeks-semenov** [comment]
COMPOSER_HOME=.composer php composer.phar create-project --prefer-dist --stability=dev skeeks/app-shop-smarty demo.ru

Поставьте этот магазин. Этот работает.  skeeks/app-shop - нужно обновить до актуальной версии cms

**Comment by mfilin** [comment]
Доброго дня. Какой установкой лучше пользоваться? После установки basic и shop-smarty лезут ошибки такого рода `Fatal error: Cannot use yii\base\Object as Object because 'Object' is a special class name in \vendor\skeeks\yii2-ckeditor\src\CKEditorPresets.php on line 11`. 

И как реагировать на такие ошибки, ведь это нужно фиксить, заменяя Object от yii2 на BaseObject...
